version: "3"

services:
  app:
    container_name: flask
    build: .
    command: python -u app.py
    ports:
      - 5000:5000
    volumes:
      - .:/app
    links:
      - mongodb

  mongodb:
    container_name: mongo
    image: mongo:latest
    hostname: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=main_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./docker-entrypoint-initdb.d/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
      - ./data:/data/db